// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBMzGJrGGhUyqc-KlHJ4lYk-_pjFTJ6c',
    appId: '1:929405354639:web:6cd5d98b9c426b9e99a6fa',
    messagingSenderId: '929405354639',
    projectId: 'infopetbo',
    authDomain: 'infopetbo.firebaseapp.com',
    databaseURL: 'https://infopetbo-default-rtdb.firebaseio.com',
    storageBucket: 'infopetbo.appspot.com',
    measurementId: 'G-7DCHT4DPH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlB3P1qvgpderGUc6K08GNjQWo3KAG-c',
    appId: '1:929405354639:android:3c184034f2dad11b99a6fa',
    messagingSenderId: '929405354639',
    projectId: 'infopetbo',
    databaseURL: 'https://infopetbo-default-rtdb.firebaseio.com',
    storageBucket: 'infopetbo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzUeYmzYqw8dWkL6XQWb2dp25TpfVQQA',
    appId: '1:929405354639:ios:8f1a7776c3206be499a6fa',
    messagingSenderId: '929405354639',
    projectId: 'infopetbo',
    databaseURL: 'https://infopetbo-default-rtdb.firebaseio.com',
    storageBucket: 'infopetbo.appspot.com',
    iosClientId: '929405354639-i4dkc89u7grkf14q1pg0qv59i972te3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.infopet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzUeYmzYqw8dWkL6XQWb2dp25TpfVQQA',
    appId: '1:929405354639:ios:8bb251552965c24399a6fa',
    messagingSenderId: '929405354639',
    projectId: 'infopetbo',
    databaseURL: 'https://infopetbo-default-rtdb.firebaseio.com',
    storageBucket: 'infopetbo.appspot.com',
    iosClientId: '929405354639-3ihdrna2d3o93f3a51aljggcau5tq79s.apps.googleusercontent.com',
    iosBundleId: 'com.example.infopet.RunnerTests',
  );
}
